### ISSUE TITLE
Give access to API for software development team to start connecting the front-end with back-end.

### ISSUE THREAD

**Issue by valto** [ecosystemos/ecosystem-mapping#10]

**Comment by oramirezmunoz** [comment]
@valto @abhijeets-ht this is the API for ecosystem mapping app: https://api-eu-central-1.graphcms.com/v2/ckojx44ir0jlm01xs82e8avjb/master

**Comment by abhijeets-ht** [comment]
@valto @oramirezmunoz Now we started working on ecosystem map integration, for that we need the dummy data to fetch API . So kindly add some of them. so that we can start posting and fetching the services
